steps:
# Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t',
    'us-east1-docker.pkg.dev/eda-processor/eda-backend-publisher/eda-backend-publisher:latest',
    '.'
  ]

# Push the Docker image to Artifact Registry
images:
- 'us-east1-docker.pkg.dev/eda-processor/eda-backend-publisher/eda-backend-publisher:latest'

# Use Cloud Logging for build logs
options:
  logging: CLOUD_LOGGING_ONLY
